apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-api-gateway
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: scanning_image_policy
    value: trivy-scan-policy-dev
  - name: scanning_source_policy
    value: trivy-scan-policy-dev
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1500m"         
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"      
  source:
    git:
      url: https://github.com/4n3w/where-for-dinner
      ref:
        branch: main
    subPath: where-for-dinner-api-gateway